const type = 'WORKER';

export default  {
  SET_START_LOADING_ACTION: `${type}:SET_START_LOADING_ACTION`,
  GET_DATA_FROM_API_REQUEST: `${type}:GET_DATA_FROM_API_REQUEST`,
  GET_DATA_FROM_API_SUCCESS: `${type}:GET_DATA_FROM_API_SUCCESS`,
  GET_DATA_FROM_API_ERROR: `${type}:GET_DATA_FROM_API_ERROR`,
  SET_PAGINATION: `${type}:SET_PAGINATION`,
  SET_FILTER_ITEM: `${type}:SET_FILTER_ITEM`,
  SET_DATA_FILTERING: `${type}:SET_DATA_FILTERING`,
};
